# Generated by Django 5.1.4 on 2024-12-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='critical_stock_level',
            new_name='min_stock_level',
        ),
    ]
